INSERT INTO DOCUMENT(AUTHOR, TITLE, TOPIC, TICKET_ID) VALUES ('Jonh Moe','The Life','science', 'c9sxR77kZH');

INSERT INTO DOCUMENT(AUTHOR, TITLE, TOPIC, TICKET_ID) VALUES ('Albert Moe','The View','media', 'c9sxR77kZ1');

INSERT INTO DOCUMENT(AUTHOR, TITLE, TOPIC, TICKET_ID) VALUES ('Jonh Mich','The Building','media', 'c9sxR77kZ2');

INSERT INTO DOCUMENT(AUTHOR, TITLE, TOPIC, TICKET_ID) VALUES ('Patrick Alfred','The Sun','business', 'c9sxR77kZ3');

INSERT INTO DOCUMENT(AUTHOR, TITLE, TOPIC, TICKET_ID) VALUES ('Mithchel Boom','The Moon','business', 'c9sxR77kZ4');

INSERT INTO DOCUMENT(AUTHOR, TITLE, TOPIC, TICKET_ID) VALUES ('Donald Jack','Opera','science', 'c9sxR77kZ5');

INSERT INTO DOCUMENT(AUTHOR, TITLE, TICKET_ID) VALUES ('Jonh Jack','The Life', 'c9sxR77kZ6');

INSERT INTO DOCUMENT(AUTHOR, TITLE, TICKET_ID) VALUES ('Boom Donald','News', 'c9sxR77kZ7');

INSERT INTO DOCUMENT(AUTHOR, TITLE, TICKET_ID) VALUES ('Jonh Patrick','Back stage', 'c9sxR77kZ8');

INSERT INTO DOCUMENT(AUTHOR, TITLE, TICKET_ID) VALUES ('Mich Alfred','Land', 'c9sxR77kZ9');

INSERT INTO DOCUMENT(AUTHOR, TITLE, TICKET_ID) VALUES ('Mithchel Donald','Moon', 'c9sxR77kZ0');

INSERT INTO DOCUMENT(AUTHOR, TITLE, TICKET_ID) VALUES ('Mithchel Jack','Greater', 'c9sxR77kZHa');